version: "3.8"

services:
  proxy:
    image: nginx:1.25.3
    ports:
      - 443:443
    volumes:
      - ./local-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./local-proxy/www.japanese-restream.org.localhost.pem:/ssl/cert.pem
      - ./local-proxy/www.japanese-restream.org.localhost-key.pem:/ssl/key.pem
  db:
    image: postgres:16.1
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  db_data:
