version: "3.8"

services:
  proxy:
    image: ghcr.io/hoishin/h2o:312635bdda2b811677d1db263cb630f69800c13e
    ports:
      - 443:443
    volumes:
      - ./local-proxy/h2o.yaml:/usr/local/etc/h2o.conf
      - ./local-proxy/www.japanese-restream.org.localhost.pem:/ssl/cert.pem
      - ./local-proxy/www.japanese-restream.org.localhost-key.pem:/ssl/key.pem
      - ./build/client/assets:/www/assets
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  db_data:
